### ISSUE TITLE
Including the Source Into the Libs Folder in Android Studio

### ISSUE THREAD

**Issue by Jayvd** [gfranks/GFMinimalNotifications#1]
Lovely library. I wanna use it i my project by adding the source (Because I need to modify a few things in it)

However after I copied the whole java and res folder into the libs folder in my project. I still cant call it in my Activity class.

Any help?

thanks

**Comment by gfranks** [comment]
Did you also copy the dependencies? That could be your problem. If that does not work, I would need a full step by step of how you copied the src files to understand where the problem may lie. I will be revising the dependencies soon to remove the use of noneoldandroids animations since I could use the native api for that.

**Comment by gfranks** [comment]
@Jayvd I have removed all dependencies associated with the library and have updated several minor issues. You may now copy them (src/res files) directly and should not see any issues. If you do, please check your build.gradle file for min/compile/target sdk versions to ensure they meet the necessary requirements (due to animation usage) or you may contact me and I can assist.

**Comment by gfranks** [comment]
Closing this because it is not an issue. You can email be directly if you need any assistance at lgfz71@gmail.com
